# Generated by Django 2.0.4 on 2018-07-10 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0002_auto_20180710_1042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='restaurants',
            new_name='Restaurant',
        ),
    ]
